CODES = {
    "AFG": "Afghanistan",
    "ALB": "Albania",
    "DZA": "Algeria",
    "ASM": "American Samoa",
    "AND": "Andorra",
    "AGO": "Angola",
    "AIA": "Anguilla",
    "ATA": "Antarctica",
    "ATG": "Antigua and Barbuda",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ABW": "Aruba",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BHS": "Bahamas",
    "BHR": "Bahrain",
    "BGD": "Bangladesh",
    "BRB": "Barbados",
    "BLR": "Belarus",
    "BEL": "Belgium",
    "BLZ": "Belize",
    "BEN": "Benin",
    "BMU": "Bermuda",
    "BTN": "Bhutan",
    "BOL": "Bolivia",
    "BIH": "Bosnia and Herzegovina",
    "BWA": "Botswana",
    "BVT": "Bouvet Island",
    "BRA": "Brazil",
    "BRN": "Brunei Darussalam",
    "BGR": "Bulgaria",
    "BFA": "Burkina Faso",
    "BDI": "Burundi",
    "CPV": "Cabo Verde",
    "KHM": "Cambodia",
    "CMR": "Cameroon",
    "CAN": "Canada",
    "CYM": "Cayman Islands",
    "CAF": "Central African Republic",
    "TCD": "Chad",
    "CHL": "Chile",
    "CHN": "China",
    "CXR": "Christmas Island",
    "COL": "Colombia",
    "COM": "Comoros",
    "COG": "Congo",
    "COK": "Cook Islands",
    "CRI": "Costa Rica",
    "HRV": "Croatia",
    "CUB": "Cuba",
    "CUW": "Curaçao",
    "CYP": "Cyprus",
    "CZE": "Czechia",
    "DNK": "Denmark",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "SLV": "El Salvador",
    "GNQ": "Equatorial Guinea",
    "ERI": "Eritrea",
    "EST": "Estonia",
    "SWZ": "Eswatini",
    "ETH": "Ethiopia",
    "FRO": "Faroe Islands",
    "FJI": "Fiji",
    "FIN": "Finland",
    "FRA": "France",
    "GUF": "French Guiana",
    "PYF": "French Polynesia",
    "GAB": "Gabon",
    "GMB": "Gambia (the)",
    "GEO": "Georgia",
    "DEU": "Germany",
    "GER": "Germany",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GRC": "Greece",
    "GRL": "Greenland",
    "GRD": "Grenada",
    "GLP": "Guadeloupe",
    "GUM": "Guam",
    "GTM": "Guatemala",
    "GGY": "Guernsey",
    "GIN": "Guinea",
    "GNB": "Guinea-Bissau",
    "GUY": "Guyana",
    "HTI": "Haiti",
    "VAT": "Holy See",
    "HND": "Honduras",
    "HKG": "Hong Kong",
    "HUN": "Hungary",
    "ISL": "Iceland",
    "IND": "India",
    "IDN": "Indonesia",
    "IRN": "Iran",
    "IRQ": "Iraq",
    "IRL": "Ireland",
    "IMN": "Isle of Man",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JPN": "Japan",
    "JEY": "Jersey",
    "JOR": "Jordan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KIR": "Kiribati",
    "KOR": "Korea",
    "KWT": "Kuwait",
    "KGZ": "Kyrgyzstan",
    "LVA": "Latvia",
    "LAT": "Latvia",
    "LBN": "Lebanon",
    "LSO": "Lesotho",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LIE": "Liechtenstein",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "MAC": "Macao",
    "MDG": "Madagascar",
    "MWI": "Malawi",
    "MYS": "Malaysia",
    "MDV": "Maldives",
    "MLI": "Mali",
    "MLT": "Malta",
    "MHL": "Marshall Islands",
    "MTQ": "Martinique",
    "MRT": "Mauritania",
    "MUS": "Mauritius",
    "MYT": "Mayotte",
    "MEX": "Mexico",
    "FSM": "Micronesia",
    "MDA": "Moldova",
    "MCO": "Monaco",
    "MNG": "Mongolia",
    "MNE": "Montenegro",
    "MSR": "Montserrat",
    "MAR": "Morocco",
    "MOZ": "Mozambique",
    "MMR": "Myanmar",
    "NAM": "Namibia",
    "NRU": "Nauru",
    "NPL": "Nepal",
    "NLD": "Netherlands",
    "NED": "Netherlands", # Alternative
    "NCL": "New Caledonia",
    "NZL": "New Zealand",
    "NIC": "Nicaragua",
    "NER": "Niger",
    "NGA": "Nigeria",
    "NIU": "Niue",
    "NFK": "Norfolk Island",
    "NOR": "Norway",
    "OMN": "Oman",
    "PAK": "Pakistan",
    "PLW": "Palau",
    "PSE": "Palestine",
    "PAN": "Panama",
    "PNG": "Papua New Guinea",
    "PRY": "Paraguay",
    "PER": "Peru",
    "PHL": "Philippines",
    "PCN": "Pitcairn",
    "POL": "Poland",
    "PRT": "Portugal",
    "PRI": "Puerto Rico",
    "QAT": "Qatar",
    "ROU": "Romania",
    "RUS": "Russian Federation",
    "RWA": "Rwanda",
    "REU": "Réunion",
    "BLM": "Saint Barthélemy",
    "SHN": "Saint Helena",
    "KNA": "Saint Kitts and Nevis",
    "LCA": "Saint Lucia",
    "MAF": "Saint Martin",
    "VCT": "Saint Vincent",
    "WSM": "Samoa",
    "SMR": "San Marino",
    "SAU": "Saudi Arabia",
    "SEN": "Senegal",
    "SRB": "Serbia",
    "SYC": "Seychelles",
    "SLE": "Sierra Leone",
    "SGP": "Singapore",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SLB": "Solomon Islands",
    "SOM": "Somalia",
    "ZAF": "South Africa",
    "SGS": "South Georgia",
    "SSD": "South Sudan",
    "ESP": "Spain",
    "LKA": "Sri Lanka",
    "SDN": "Sudan",
    "SUR": "Suriname",
    "SWE": "Sweden",
    "CHE": "Switzerland",
    "SYR": "Syrian Arab Republic",
    "TWN": "Taiwan",
    "TJK": "Tajikistan",
    "TZA": "Tanzania",
    "THA": "Thailand",
    "TLS": "Timor-Leste",
    "TGO": "Togo",
    "TKL": "Tokelau",
    "TON": "Tonga",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TKM": "Turkmenistan",
    "TCA": "Turks and Caicos Islands",
    "TUV": "Tuvalu",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "ARE": "United Arab Emirates",
    "GBR": "Great Britain",
    "USA": "United States of America",
    "URY": "Uruguay",
    "UZB": "Uzbekistan",
    "VUT": "Vanuatu",
    "VEN": "Venezuela",
    "VNM": "Viet Nam",
    "VGB": "Virgin Islands (British)",
    "VIR": "Virgin Islands (U.S.)",
    "WLF": "Wallis and Futuna",
    "ESH": "Western Sahara",
    "YEM": "Yemen",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe",
    "ALA": "Åland Islands",
    "EUR": "Not_set"
}

CODES2 = {'EUR':'EUR','AFG': 'AFG','ALB': 'ALB', 'DZA': 'DZA', 'ASM': 'ASM', 'AND': 'AND', 'AGO': 'AGO', 'AIA': 'AIA', 'ATA': 'ATA', 'ATG': 'ATG', 'ARG': 'ARG', 'ARM': 'ARM', 'ABW': 'ABW', 'AUS': 'AUS', 'AUT': 'AUT', 'AZE': 'AZE', 'BHS': 'BHS', 'BHR': 'BHR', 'BGD': 'BGD', 'BRB': 'BRB', 'BLR': 'BLR', 'BEL': 'BEL', 'BLZ': 'BLZ', 'BEN': 'BEN', 'BMU': 'BMU', 'BTN': 'BTN', 'BOL': 'BOL', 'BES': 'BES', 'BIH': 'BIH', 'BWA': 'BWA', 'BVT': 'BVT', 'BRA': 'BRA', 'IOT': 'IOT', 'BRN': 'BRN', 'BGR': 'BGR', 'BFA': 'BFA', 'BDI': 'BDI', 'CPV': 'CPV', 'KHM': 'KHM', 'CMR': 'CMR', 'CAN': 'CAN', 'CYM': 'CYM', 'CAF': 'CAF', 'TCD': 'TCD', 'CHL': 'CHL', 'CHN': 'CHN', 'CXR': 'CXR', 'CCK': 'CCK', 'COL': 'COL', 'COM': 'COM', 'COD': 'COD', 'COG': 'COG', 'COK': 'COK', 'CRI': 'CRI', 'HRV': 'HRV', 'CUB': 'CUB', 'CUW': 'CUW', 'CYP': 'CYP', 'CZE': 'CZE', 'CIV': 'CIV', 'DNK': 'DNK', 'DJI': 'DJI', 'DMA': 'DMA', 'DOM': 'DOM', 'ECU': 'ECU', 'EGY': 'EGY', 'SLV': 'SLV', 'GNQ': 'GNQ', 'ERI': 'ERI', 'EST': 'EST', 'SWZ': 'SWZ', 'ETH': 'ETH', 'FLK': 'FLK', 'FRO': 'FRO', 'FJI': 'FJI', 'FIN': 'FIN', 'FRA': 'FRA', 'GUF': 'GUF', 'PYF': 'PYF', 'ATF': 'ATF', 'GAB': 'GAB', 'GMB': 'GMB', 'GEO': 'GEO', 'DEU': 'DEU','GER': 'GER','GHA': 'GHA', 'GIB': 'GIB', 'GRC': 'GRC', 'GRL': 'GRL', 'GRD': 'GRD', 'GLP': 'GLP', 'GUM': 'GUM', 'GTM': 'GTM', 'GGY': 'GGY', 'GIN': 'GIN', 'GNB': 'GNB', 'GUY': 'GUY', 'HTI': 'HTI', 'HMD': 'HMD', 'VAT': 'VAT', 'HND': 'HND', 'HKG': 'HKG', 'HUN': 'HUN', 'ISL': 'ISL', 'IND': 'IND', 'IDN': 'IDN', 'IRN': 'IRN', 'IRQ': 'IRQ', 'IRL': 'IRL', 'IMN': 'IMN', 'ISR': 'ISR', 'ITA': 'ITA', 'JAM': 'JAM', 'JPN': 'JPN', 'JEY': 'JEY', 'JOR': 'JOR', 'KAZ': 'KAZ', 'KEN': 'KEN', 'KIR': 'KIR', 'PRK': 'PRK', 'KOR': 'KOR', 'KWT': 'KWT', 'KGZ': 'KGZ', 'LAO': 'LAO', 'LVA': 'LVA', 'LAT': 'LAT', 'LBN': 'LBN', 'LSO': 'LSO', 'LBR': 'LBR', 'LBY': 'LBY', 'LIE': 'LIE', 'LTU': 'LTU', 'LUX': 'LUX', 'MAC': 'MAC', 'MDG': 'MDG', 'MWI': 'MWI', 'MYS': 'MYS', 'MDV': 'MDV', 'MLI': 'MLI', 'MLT': 'MLT', 'MHL': 'MHL', 'MTQ': 'MTQ', 'MRT': 'MRT', 'MUS': 'MUS', 'MYT': 'MYT', 'MEX': 'MEX', 'FSM': 'FSM', 'MDA': 'MDA', 'MCO': 'MCO', 'MNG': 'MNG', 'MNE': 'MNE', 'MSR': 'MSR', 'MAR': 'MAR', 'MOZ': 'MOZ', 'MMR': 'MMR', 'NAM': 'NAM', 'NRU': 'NRU', 'NPL': 'NPL', 'NLD': 'NLD', 'NED': 'NED', 'NCL': 'NCL', 'NZL': 'NZL', 'NIC': 'NIC', 'NER': 'NER', 'NGA': 'NGA', 'NIU': 'NIU', 'NFK': 'NFK', 'MNP': 'MNP', 'NOR': 'NOR', 'OMN': 'OMN', 'PAK': 'PAK', 'PLW': 'PLW', 'PSE': 'PSE', 'PAN': 'PAN', 'PNG': 'PNG', 'PRY': 'PRY', 'PER': 'PER', 'PHL': 'PHL', 'PCN': 'PCN', 'POL': 'POL', 'PRT': 'PRT', 'PRI': 'PRI', 'QAT': 'QAT', 'MKD': 'MKD', 'ROU': 'ROU', 'RUS': 'RUS', 'RWA': 'RWA', 'REU': 'REU', 'BLM': 'BLM', 'SHN': 'SHN', 'KNA': 'KNA', 'LCA': 'LCA', 'MAF': 'MAF', 'SPM': 'SPM', 'VCT': 'VCT', 'WSM': 'WSM', 'SMR': 'SMR', 'STP': 'STP', 'SAU': 'SAU', 'SEN': 'SEN', 'SRB': 'SRB', 'SYC': 'SYC', 'SLE': 'SLE', 'SGP': 'SGP', 'SXM': 'SXM', 'SVK': 'SVK', 'SVN': 'SVN', 'SLB': 'SLB', 'SOM': 'SOM', 'ZAF': 'ZAF', 'SGS': 'SGS', 'SSD': 'SSD', 'ESP': 'ESP', 'LKA': 'LKA', 'SDN': 'SDN', 'SUR': 'SUR', 'SJM': 'SJM', 'SWE': 'SWE', 'CHE': 'CHE', 'SYR': 'SYR', 'TWN': 'TWN', 'TJK': 'TJK', 'TZA': 'TZA', 'THA': 'THA', 'TLS': 'TLS', 'TGO': 'TGO', 'TKL': 'TKL', 'TON': 'TON', 'TTO': 'TTO', 'TUN': 'TUN', 'TUR': 'TUR', 'TKM': 'TKM', 'TCA': 'TCA', 'TUV': 'TUV', 'UGA': 'UGA', 'UKR': 'UKR', 'ARE': 'ARE', 'GBR': 'GBR', 'UMI': 'UMI', 'USA': 'USA', 'URY': 'URY', 'UZB': 'UZB', 'VUT': 'VUT', 'VEN': 'VEN', 'VNM': 'VNM', 'VGB': 'VGB', 'VIR': 'VIR', 'WLF': 'WLF', 'ESH': 'ESH', 'YEM': 'YEM', 'ZMB': 'ZMB', 'ZWE': 'ZWE', 'ALA': 'ALA'}