# Generated by Django 3.2.5 on 2022-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220531_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='ename',
            field=models.CharField(choices=[('HKLH21', 'Helsinki Half Marathon'), ('OMVH22', 'OMV Halbmarathon Altötting')], default='Helsinki Half Marathon', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competitor',
            name='ccode',
            field=models.CharField(default='Y6CF5W', help_text='max 6 chars', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ecode',
            field=models.CharField(default='KBZWDB', max_length=6, primary_key=True, serialize=False),
        ),
    ]
