# Generated by Django 3.2.5 on 2022-05-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20220531_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='ccode',
            field=models.CharField(default='9B7UFN', help_text='max 6 chars', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ecode',
            field=models.CharField(default='GQG7AJ', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='race',
            name='ename',
            field=models.CharField(choices=[('HKLH21', 'Helsinki Half Marathon'), ('OMVH22', 'OMV Halbmarathon Altötting'), ('RUSH21', 'Moscow Mountain Madness'), ('EKBH22', 'Half Marathon Race RF Yekaterinburg'), ('SWEH22', '6 lakes')], max_length=100, null=True),
        ),
    ]
