# Generated by Django 3.2.5 on 2022-05-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20220601_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='ccode',
            field=models.CharField(default='3VUX27', help_text='max 6 chars', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ecode',
            field=models.CharField(default='CUP2EV', max_length=6, primary_key=True, serialize=False),
        ),
    ]
