# Generated by Django 3.2.5 on 2022-05-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20220601_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='ename',
        ),
        migrations.AddField(
            model_name='race',
            name='ecode',
            field=models.CharField(choices=[('Helsinki Half Marathon', 'HKLH21'), ('OMV Halbmarathon Altötting', 'OMVH22'), ('Moscow Mountain Madness', 'RUSH21'), ('Half Marathon Race RF Yekaterinburg', 'EKBH22'), ('6 lakes', 'SWEH22')], help_text='This is how your event name is presented on the site', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='ccode',
            field=models.CharField(default='ERXJ3N', help_text='max 6 chars', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ecode',
            field=models.CharField(default='46NJSZ', max_length=6, primary_key=True, serialize=False),
        ),
    ]
