# Generated by Django 3.2.5 on 2022-06-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20220602_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='ccode',
            field=models.CharField(default='3RH2NS', help_text='max 6 chars', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ecode',
            field=models.CharField(default='GASC8X', max_length=6, primary_key=True, serialize=False),
        ),
    ]
