# Generated by Django 3.2.5 on 2022-06-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20220602_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='ccode',
            field=models.CharField(default='X2E29N', help_text='max 6 chars', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('opt0', 'New sport event'), ('opt1', 'Results service application'), ('opt2', 'Request for a membership of Run4Fun team'), ('opt3', 'Incorrect information notification'), ('opt4', 'Service feedback and development ideas'), ('opt5', 'Other service request'), ('opt6', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='ecode',
            field=models.CharField(default='J7J26W', max_length=6, primary_key=True, serialize=False),
        ),
    ]
