# Generated by Django 3.2.5 on 2022-06-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20220602_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventorganizerperson',
            old_name='event',
            new_name='event_organizer',
        ),
        migrations.AlterField(
            model_name='competitor',
            name='ccode',
            field=models.CharField(default='EYX7NN', help_text='max 6 chars', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ecode',
            field=models.CharField(default='RARTJ9', max_length=6, primary_key=True, serialize=False),
        ),
    ]
