# Generated by Django 3.2.5 on 2022-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20220603_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='ccode',
            field=models.CharField(default='HUGAS7', help_text='max 6 chars', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ecode',
            field=models.CharField(default='NPSWHR', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
