# Generated by Django 3.2.5 on 2022-06-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20220603_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='ccode',
            field=models.CharField(default='6DDVSZ', help_text='max 6 chars', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ecode',
            field=models.CharField(default='CQY2G8', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='race',
            name='ecode',
            field=models.CharField(choices=[('Helsinki Half Marathon', 'HKLH21'), ('OMV Halbmarathon Altötting', 'OMVH22'), ('Königsschlösser Romantik Marathon', 'KÖNH18'), ('Moscow Mountain Madness', 'RUSH21'), ('Half Marathon Race RF Yekaterinburg', 'EKBH22'), ('6 lakes', 'SWEH22')], help_text='This is how your event name is presented on the site', max_length=100, null=True),
        ),
    ]
